### ISSUE TITLE
location/cmd bar

### ISSUE THREAD

**Issue by dominictarr** [dominictarr/patchbay#24]
@clehner's search is pretty handy, but it gets in the way when the screen is narrow.

![screenshot_narrow-search](https://cloud.githubusercontent.com/assets/259374/16607258/3914b084-4393-11e6-8a2d-714b4e2e33e0.png)

my idea: move to just below the tabs, like the browser location bar.

then, on whatever tab you are on, the location bar shows the _raw_ location. i.e. the message hash, feed id, /public /private, etc or search term.

The tab name can then be a human readable name (i.e. feed name or first line of root message in thread)

we can also use this for things like invites codes. just paste the invite code into the location bar to use it.

**Comment by dominictarr** [comment]
Oh, looking at the code, I have realized that the searchbox basically _is_ a location bar.
it just needs to update to show the current location...

It's a great sign you are doing things right (modular) when you want to do a thing and you realize that it's already done, just a matter of composing. All i need to do is implement a screen_view that does invite codes and we have invite codes!

**Comment by clehner** [comment]
when I added the search box I was thinking of it like a command line search prompt, like in vim or mutt, or surf. i set it to only be visible when active to take up less space. but changing it to be more like a location bar i think is fine as that is a familiar UI item and is more general/powerful.

**Comment by dominictarr** [comment]
hmm, well it doesn't disappear anymore for me. maybe that was after @evbogue's css? 
anyway it is useful to keep it open so you can grab the ids though

**Comment by evbogue** [comment]
@dominic Yes. I made it appear because I couldn't see it.

**Comment by evbogue** [comment]
I think it's cool to move the location/searchbar wherever it needs to go.

**Comment by evbogue** [comment]
This can be closed.
