### ISSUE TITLE
Uncaught Error: Cannot find module 'hyperlightbox'

### ISSUE THREAD

**Issue by cryptix** [dominictarr/patchbay#3]
All I get is a white screen and the title as an error in the dev tools.

![modulenotfound](https://cloud.githubusercontent.com/assets/111202/16284041/9a656e92-38cf-11e6-8d5d-2beb792a56a0.png)

[npm ls](https://github.com/dominictarr/patchbay/files/328779/npm_ls.txt)

**Comment by dominictarr** [comment]
thanks, fixed in 1.0.6

**Comment by cryptix** [comment]
Yup, that is gone but `hypertabs` is also missing.

**Comment by dominictarr** [comment]
okay, I had cloned it my self and made sure it is working. use patchbay@1.0.7

I don't understand why yet, but you'll need to run with js crypto.
start with `CHLORIDE_JS=1 electro index.js`
https://github.com/dominictarr/patchbay/issues/2#issuecomment-227343966

**Comment by dominictarr** [comment]
actually, use 1.1.0 (well, just master since I guess you are cloning, as per current instructions ;) and you'll get automatic reconnecting to your sbot.

**Comment by cryptix** [comment]
Okay. 1.1.0 also fixed #4, when running with `CHLORIDE_JS=1`.
