### ISSUE TITLE
Make replying more intuitive

### ISSUE THREAD

**Issue by evbogue** [dominictarr/patchbay#40]
I've noticed from on-boarding a few people into the lite client that it's not intuitive how to reply to a post in Patchbay. Most people seem to reply with a new message in the stream, which isn't the correct UX for threads. 

I don't have any ideas about how to fix this, but I figure I'd open an issue about it.

**Comment by dominictarr** [comment]
hmm, how about a "reply" button that opens the thread in a lightbox? or takes you to the thread?

**Comment by benjajuarez** [comment]
simple idea: why not 
add a simple text of **"reply" next to the hour**. 

this way people would click it. I would

**Comment by evbogue** [comment]
Beyond the UX issue, I've discovered the actual issue here is threads do not work when you're running the lite client at a port and serving it up at a url. When you click a thread, it just opens patchbay in a new browser window. 

Threads do work when you save the lite client to your desktop. This is also a faster experience because the browser isn't downloading 2mb of javascript every time you reload the page.

@benjajuarez are you using the lite client from ssb.evbogue.com or did you download the patchbay-latest html file from my site?

**Comment by benjajuarez** [comment]
2.  downloaded the patchbay-latest html file from [your site](https://evbogue.com/patchbayinstall/)

**Comment by benjajuarez** [comment]
@dominictarr [writing 1984 fanfic where winston enjoys his totalitarian society ironically](https://twitter.com/dominictarr)!!! I'd love to read that!!!!

**Comment by evbogue** [comment]
@benjajuarez Let's keep this thread focused on development, por fa.

**Comment by benjajuarez** [comment]
my bad

**Comment by dominictarr** [comment]
@evbogue do you have ssb-links and ssb-query installed?

**Comment by evbogue** [comment]
@dominictarr I didn't have them installed on my server. Installing ssb-links and ssb-query fixed the permalinks issue at http://ssb.evbogue.com/

**Comment by dominictarr** [comment]
@evbogue aha, I see it. when you click re: link it opens it in a new tab.
I put this in https://github.com/dominictarr/patchbay/blob/master/modules/tabs.js#L79-L80
and it stopped doing this (weird thing is that it only happens when use use http served html, but not when you open it as a file) the reply links must be being triggered via a different path...

**Comment by dominictarr** [comment]
Aha, no, the problem at
https://github.com/dominictarr/patchbay/blob/master/modules/tabs.js#L84

Which assumes that any http link is external. Instead, we need to check if it's on a different domain,
and treat links to the same domain as local links. I'll fix this.

**Comment by dominictarr** [comment]
fixed in 1.7.6!

**Comment by dominictarr** [comment]
oops, no i broke other stuff...

**Comment by dominictarr** [comment]
okay fixed in 1.7.7

**Comment by evbogue** [comment]
confirmed fixed when deployed to ssb.evbogue.com

**Comment by evbogue** [comment]
I believe 1.7.7 and #41 resolve this issue.
