### ISSUE TITLE
TypeError: Param 1 must by of type object

### ISSUE THREAD

**Issue by evbogue** [dominictarr/patchbay#5]
I've hit error this a few times, so making an issue.

When I reach the installation step where I am installing sbot plugins, I get this error
```
[ev@arch patchbay]$ sbot plugins.install ssb-links ssb-query
error loading sodium bindings: Cannot find module 'chloridedown/build/Release/sodium'
falling back to javascript version.
TypeError: Param 1 must by of type object
Install a plugin to Scuttlebot.

install {nodeModule} [--from path]

Calls out to npm to install a package into `~/.ssb/node_modules`.

-   nodeModule (string): The name of the plugin to install. Uses npm's module package-name rules.
-   from (string): A location to install from (directory path, url, or any location that npm accepts for its install command).
```

Is there a manual way to install the plugins?

**Comment by evbogue** [comment]
Additional info

```
 npm ls secure-scuttlebutt -g
npm info it worked if it ends with ok
npm info using npm@3.9.5
npm info using node@v6.2.1
/usr/lib
├─┬ scuttlebot@8.3.2
│ └── secure-scuttlebutt@15.2.3
└─┬ ssb-patchwork@2.8.4
  └─┬ scuttlebot@8.2.1
    └── secure-scuttlebutt@15.2.2

npm info ok
```

**Comment by evbogue** [comment]
I should also note that ssb-links and ssb-query are already installed in my .ssb folder.

When I try to launch patchbay I get this error:

```
$ electro index.js

/usr/lib/node_modules/electro/index.js:54
  mainWindow.loadUrl('file://' + path.join(__dirname, 'index.html') + '?' +
             ^

TypeError: mainWindow.loadUrl is not a function
    at EventEmitter.next (/usr/lib/node_modules/electro/index.js:54:14)
    at emitOne (events.js:101:20)
    at EventEmitter.emit (events.js:188:7)
```

**Comment by evbogue** [comment]
Issue 2 appears to have been solved in https://github.com/dominictarr/patchbay/issues/2

Reinstalling Electro to see if that helps get Patchbay running.

**Comment by evbogue** [comment]
Ok, after reinstalling Electro Patchbay runs for me. However, I am not seeing any data inside Electron. 
![2016-06-24-231416_698x439_scrot](https://cloud.githubusercontent.com/assets/2468866/16354670/7a942afc-3a61-11e6-93fc-e98fb97c5ff4.png)

**Comment by dominictarr** [comment]
can you check the dev tools? `ctrl-shift-i`
what node version are you on?
also, my hunch is it's this: https://github.com/dominictarr/patchbay/issues/6

**Comment by evbogue** [comment]
Node 6.2.1

What am I looking for in dev tools? The console is empty.

**Comment by evbogue** [comment]
`CHLORIDE_JS=1 electro index.js` doesn't solve the problem for me.

**Comment by evbogue** [comment]
Is there a way to run Patchbay in a browser instead of Electron?

**Comment by dominictarr** [comment]
@evbogue hmm, hopefully some error message...
not yet, but I'm working on that now. what patchbay git commit are you on?

**Comment by evbogue** [comment]
@dominictarr Git commit: Master. 1.1.0 27e92625a95571a37337ba2095d5d17499d43195

**Comment by dominictarr** [comment]
can you update to 006f1095e4874780ffafca24791259c6124c9bc3 ?
run sbot@8.3.2 or I have also confirmed that patchwork@6c8670658ad9d20bb3e815052eafc1721bed4000 works.

**Comment by dominictarr** [comment]
can you post your `npm ls`?

**Comment by evbogue** [comment]
Not working with sbot@8.3.2. I also tried cloning sbot@8.3.2 down and building it in a non-global folder. Sbot works fine with micropub, but doesn't load into the patchbay frontend. 

![2016-06-26-104410_1366x768_scrot](https://cloud.githubusercontent.com/assets/2468866/16363275/6e2c6b46-3b8b-11e6-9dcd-b6f83bb55d3d.png)

```
patchbay@1.1.1 /home/ev/builds/patchbay
├─┬ cont@1.0.3
│ ├── continuable@1.2.0
│ ├─┬ continuable-para@1.2.0
│ │ ├─┬ continuable-hash@0.1.4
│ │ │ └── continuable@1.1.8
│ │ └─┬ continuable-list@0.1.6
│ │   └── continuable@1.1.8
│ └── continuable-series@1.2.0
├── depject@0.1.0
├── hyperlightbox@0.0.0
├─┬ hyperscript@1.4.7
│ ├── browser-split@0.0.0
│ ├─┬ class-list@0.1.1
│ │ └── indexof@0.0.1
│ └── html-element@1.3.0
├── hypertabs@1.0.0
├─┬ mime-types@2.1.11
│ └── mime-db@1.23.0
├── moment@2.13.0
├── pull-cat@1.1.9
├── pull-next@0.0.0
├── pull-paramap@1.1.6
├─┬ pull-reconnect@0.0.1
│ └── pull-defer@0.2.2
├─┬ pull-scroll@0.2.0
│ ├─┬ is-visible@2.0.4
│ │ ├── iselement@1.0.0
│ │ └── style-properties@1.2.1
│ ├── observable@2.1.4
│ ├── pull-pause@0.0.0
│ └── request-animation-loop@0.1.0
├── pull-stream@3.4.3
├── split-buffer@1.0.0
├── ssb-avatar@0.0.2
├─┬ ssb-client@3.1.1
│ ├── explain-error@1.0.1
│ ├─┬ secret-stack@2.5.1
│ │ ├── hoox@0.0.1
│ │ ├── map-merge@1.1.0
│ │ ├─┬ muxrpc@6.3.3
│ │ │ ├── packet-stream@2.0.0
│ │ │ ├─┬ packet-stream-codec@1.1.1
│ │ │ │ └── pull-through@1.0.18
│ │ │ └── pull-goodbye@0.0.1


│ │ │ │ └── pull-through@1.0.18
│ │ │ └── pull-goodbye@0.0.1
│ │ ├─┬ non-private-ip@1.3.0
│ │ │ └── ip@0.3.3
│ │ ├─┬ pull-inactivity@2.1.1
│ │ │ ├── pull-abortable@4.0.0
│ │ │ └── pull-stream@2.26.1
│ │ ├─┬ pull-stream@2.27.0
│ │ │ └── pull-core@1.1.0
│ │ ├─┬ secret-handshake@0.4.1
│ │ │ ├── deep-equal@1.0.1
│ │ │ ├─┬ pull-box-stream@1.0.11
│ │ │ │ └── increment-buffer@1.0.0
│ │ │ ├─┬ pull-handshake@1.1.3
│ │ │ │ ├── pull-delayed-sink@1.0.0
│ │ │ │ └── pull-pair@1.0.0
│ │ │ ├── pull-pair@1.1.0
│ │ │ ├── pull-pushable@2.0.1
│ │ │ └─┬ pull-reader@1.2.5
│ │ │   └─┬ bl@1.1.2
│ │ │     └─┬ readable-stream@2.0.6
│ │ │       ├── core-util-is@1.0.2
│ │ │       ├── isarray@1.0.0
│ │ │       ├── process-nextick-args@1.0.7
│ │ │       ├── string_decoder@0.10.31
│ │ │       └── util-deprecate@1.0.2
│ │ └─┬ stream-to-pull-stream@1.6.10
│ │   └── looper@3.0.0
│ └─┬ ssb-config@2.0.0
│   ├── deep-extend@0.4.1
│   ├─┬ osenv@0.1.3
│   │ ├── os-homedir@1.0.1
│   │ └── os-tmpdir@1.0.1
│   └─┬ rc@1.1.6
│     ├── ini@1.3.4
│     ├── minimist@1.2.0
│     └── strip-json-comments@1.0.4
├─┬ ssb-keys@5.1.1
│ ├── blake2s@1.0.1
│ ├─┬ chloride@2.1.1
│ │ ├─┬ chloridedown@1.0.22
│ │ │ └── nan@2.3.5
│ │ ├─┬ sodium-browserify@1.1.2
│ │ │ ├─┬ libsodium-wrappers@0.2.12
│ │ │ │ └── libsodium@0.2.12

│ │ │ ├─┬ libsodium-wrappers@0.2.12
│ │ │ │ └── libsodium@0.2.12
│ │ │ ├─┬ sha.js@2.4.5
│ │ │ │ └── inherits@2.0.1
│ │ │ └── tweetnacl@0.14.3
│ │ └─┬ sodium-browserify-tweetnacl@0.1.0
│ │   ├── ed2curve@0.1.4
│ │   └── tweetnacl-auth@0.3.0
│ ├── deep-equal@0.2.2
│ ├── hmac@1.0.1
│ ├─┬ mkdirp@0.5.1
│ │ └── minimist@0.0.8
│ ├── private-box@0.0.3
│ └─┬ ssb-ref@2.3.0
│   ├── ip-regex@1.0.3
│   └── is-valid-domain@0.0.2
├─┬ ssb-markdown@3.0.0
│ ├── emoji-named-characters@1.0.2
│ ├── ssb-marked@0.5.4
│ └── ssb-msgs@5.2.0
├── ssb-mentions@0.1.0
├── ssb-sort@0.0.0
└─┬ suggest-box@2.1.0
  └── textarea-caret-position@0.1.1
```

**Comment by evbogue** [comment]
I tried to post in Patchbay, and got this error.

![2016-06-26-110821_720x585_scrot](https://cloud.githubusercontent.com/assets/2468866/16363401/6f8f78fe-3b8e-11e6-9821-c361f440fe2f.png)

**Comment by evbogue** [comment]
It should be noted: `plugins.install` works for me now!

**Comment by dominictarr** [comment]
thanks... this is quite perplexing.
* obviously scuttlebutt is working
* obviously ssb-client is working (because patchwork & micropub work)

some reason it's not working _in electron_ which is weird.
I recently added a automatic reconnection, and just realized now that I had removed error logging when reconnect fails. can you try again, with `CHLIRODE_JS=1 electro index.js` as well as `electro index.js`?

it's gotta be something about running chloride in electro

**Comment by evbogue** [comment]
I did a pull and tried both `CHLORIDE_JS=1 electro index.js` and `electro index.js` 

With the recent commits, now nothing is showing up at all for me inside electron.

I also tried to get patchbay working on my other computer, which has a more recent install of sbot + patchwork, and had the same results. Though it's the same system specs, Arch with the latest version of Node and npm.

**Comment by evbogue** [comment]
Got an error in the console this time: 

`/home/ev/builds/patchbay/sbot-api.js:24 Uncaught SyntaxError: Unexpected token .`

**Comment by dominictarr** [comment]
sorry, I totally pushed a syntax error.

**Comment by dominictarr** [comment]
pull the latest, should work now.

**Comment by dominictarr** [comment]
:pray:

**Comment by evbogue** [comment]
@dominic Working with 'CHLORIDE_JS=1'

**Comment by dominictarr** [comment]
YUSS!!!
