### ISSUE TITLE
exports.isLongTerm is not a function

### ISSUE THREAD

**Issue by kyrias** [dominictarr/patchbay#58]
All of a sudden I get

```
Uncaught TypeError: exports.isLongterm is not a function
```

at `network.js:41` when trying to open the `/network` page.

**Comment by kyrias** [comment]
(Also, anytime that happens I get a new tab called "errors" containing nothing..)

**Comment by dominictarr** [comment]
fixed in 3.6.1

**Comment by kyrias** [comment]
Awesome!  (Though still occasionally get that errors tab with no content.)
